version: '3'

services:
#  web:
#    image: nginx:latest
#    ports:
#      - "80:80"
#    container_name: nginx
#    depends_on:
#      - backend

#  backend:
#    image: openjdk:latest
#    container_name: backend
#    depends_on:
#      - web
#      - db

  db:
    image: mysql:8.0
    restart: unless-stopped
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: preorder
      MYSQL_USER: eje
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8078:8080

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  mysql_data:
