spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/preorder?useSSL=false
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update # or create-drop if you want to recreate tables on each start
    show-sql: true