server:
  port: 8082
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/preorder?useSSL=false
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  cloud:
    config:
      enabled: false

  jwt:
    secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
user:
  service:
    url: http://localhost:8080