server:
  port: 8080
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/preorder?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: preorder.project1@gmail.com
    password: ucmn ngyz cwze zapc
    properties:
      mail:
        smtp:
          auth: true
          starttls: # 추가 안하면 SMTPSendFailedException
            enable: true

  servlet:
    multipart:
      enabled: true  # multipart 처리를 활성화
      max-file-size: 2MB  # 최대 파일 크기 제한
      max-request-size: 2MB  # 최대 요청 크기 제한

  cloud:
    config:
      enabled: false
  jwt:
    secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
